language: go
sudo: false
dist: trusty
before_install:
- export PATH=$PATH:$HOME/.local/bin
install:
- go get -v github.com/spf13/hugo
- git clone https://github.com/digitalcraftsman/hugo-strata-theme themes/hugo-strata-theme
- go get -t ./...
script:
- mkdir static/images/thumbs
- go build tools/make_thumbnail.go
- "./make_thumbnail"
- rm make_thumbnail
- hugo
deploy:
  provider: s3
  access_key_id: AKIAIP3S2GWSCPSVDGJQ
  secret_access_key:
    secure: Y81/VyxlCKPqSR+0YYZQvequAZizSd/HBdF6ZHYSv8NuHlw0iEC9GOlUhlL6zWa0SWx6kr5Mxv3fawhZxg8K75JxjEBFjMF40sLEV0K8ULhklL5lhQ7cRt5xLJELxm/x2SCkF2bt7rPruFABi/tVsFZCKxbDZVurNb+hjYTUnBju6237SCxw/821ZM7WZbsjUQb5KdnCKUAE0heeIjxGqemxW47nLzDM+75OtdALQDqc807amfS7bzVAFq//l36gJd0OatFboRdXLVqDRlwdrABRv0njJBooQ6wgjS+n3AlmDaSdVB6HzmWetggRQ/WaXvoyL1gTpqBL8+OiiRehP8n1KJhS37J9+PcrgWf8IdXxVYKxLaVHV5423XC1spQb80zoLMhhjcZpxzcpGieMQJso3iC9q05DBj2RUhpg2HqGaoShEhfkkVZ03tWVLH8pmM7WQWfNSJ4gOwX+umhHG5GLbGMrNQnyqK/WQNAWFWF7yR17JW0ztHwsEOC1m/qrp062DqTdn8ZsCPujTKPnSd8gW3iOl7To3r9aRkUnVMqRPPi+pcm+fElS9ibiiLxce53wsrUr7HI/PAmmQEjm7ZO1Vre1dtUZCs2hcKV6eqfOM6GfDgzDki+iWyDRyt6ByH3zIKtOAMvQzGIBfWiDn5Hz38kXHlXiPmIQGolhaHM=
  bucket: villaashika-origin.s3-website-ap-northeast-1.amazonaws.com
  local_dir: public
  acl: public_read
  skip_cleanup: true

notifications:
  email:
    on_failure: always

